const CSC_DISTANCE_SCHEME =
  "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-distance-learning-scholarships-candidates/";
const CSC_DISTANCE_COURSES =
  "https://cscuk.fcdo.gov.uk/commonwealth-distance-learning-scholarships-eligible-courses/";

const DISTANCE_CYCLE = {
  academicYear: "2026/27",
  applicationStatus: "closed",
};

function distanceDescription({ course, university, theme }) {
  return [
    `Commonwealth Distance Learning Scholarship: ${course} at ${university} (${DISTANCE_CYCLE.academicYear}).`,
    `Development theme: ${theme}.`,
    "These scholarships fund remote master's study for candidates from eligible least developed and middle-income Commonwealth countries who remain in their home country while studying.",
    "Applications are made through participating UK universities that hold CSC distance learning awards for this course.",
    `CSC distance learning applications for ${DISTANCE_CYCLE.academicYear} are currently ${DISTANCE_CYCLE.applicationStatus}.`,
    `Eligible courses listing: ${CSC_DISTANCE_COURSES}`,
    `Scheme overview: ${CSC_DISTANCE_SCHEME}`,
  ].join(" ");
}

/** 2026 CSC Distance Learning eligible courses (official listing). */
const COMMONWEALTH_DISTANCE_COURSES = [
  {
    slug: "leeds-beckett-responsible-tourism",
    university: "Leeds Beckett University",
    course: "MSc Responsible Tourism Management",
    theme: "Access, inclusion and opportunity",
    url: "https://www.leedsbeckett.ac.uk/courses/responsible-tourism-management-msc/",
  },
  {
    slug: "open-university-online-teaching",
    university: "Open University",
    course: "MA Online Teaching",
    theme: "Access, inclusion and opportunity",
    url: "https://www.open.ac.uk/postgraduate/qualifications/f98",
  },
  {
    slug: "sas-human-rights",
    university: "School of Advanced Study, University of London",
    course: "MA Human Rights",
    theme: "Access, inclusion and opportunity",
    url: "https://www.london.ac.uk/study/courses/postgraduate/ma-human-rights",
  },
  {
    slug: "leeds-disability-studies",
    university: "University of Leeds",
    course: "MSc Disability Studies, Rights and Inclusion",
    theme: "Access, inclusion and opportunity",
    url: "https://www.leeds.ac.uk/homepage/275/online-masters-and-postgraduate-courses-in-disability-studies-rights-and-inclusion",
  },
  {
    slug: "southampton-gerontology",
    university: "University of Southampton",
    course: "MSc Gerontology",
    theme: "Access, inclusion and opportunity",
    url: "https://www.southampton.ac.uk/courses/gerontology-distance-learning-masters-msc",
  },
  {
    slug: "southampton-global-ageing",
    university: "University of Southampton",
    course: "MSc Global Ageing and Policy",
    theme: "Access, inclusion and opportunity",
    url: "https://www.southampton.ac.uk/courses/global-ageing-policy-distance-learning-masters-msc",
  },
  {
    slug: "cranfield-sustainability",
    university: "Cranfield University",
    course: "MSc Sustainability",
    theme: "Promoting innovation and entrepreneurship",
    url: "https://www.cranfield.ac.uk/sustainabilitymsc",
  },
  {
    slug: "bangor-agroforestry",
    university: "Bangor University",
    course: "MSc Agroforestry and Food Security",
    theme: "Science and technology for development",
    url: "https://www.bangor.ac.uk/courses/postgraduate-taught/agroforestry-and-food-security-msc-msc",
  },
  {
    slug: "bangor-tropical-forestry",
    university: "Bangor University",
    course: "MSc Tropical Forestry",
    theme: "Science and technology for development",
    url: "https://www.bangor.ac.uk/courses/postgraduate-taught/tropical-forestry-msc-msc",
  },
  {
    slug: "heriot-watt-renewable-energy",
    university: "Heriot-Watt University",
    course: "MSc Renewable and Sustainable Energy Transition",
    theme: "Science and technology for development",
    url: "https://www.hw.ac.uk/study/postgraduate/renewable-sustainable-energy-transition",
  },
  {
    slug: "heriot-watt-construction-pm",
    university: "Heriot-Watt University",
    course: "MSc Construction Project Management",
    theme: "Science and technology for development",
    url: "https://www.hw.ac.uk/online/study/postgraduate/construction-project-management",
  },
  {
    slug: "loughborough-water-engineering",
    university: "Loughborough University",
    course: "MSc Water Engineering for Development",
    theme: "Science and technology for development",
    url: "https://www.lboro.ac.uk/study/postgraduate/masters-degrees/a-z/water-engineering-development-distance/",
  },
  {
    slug: "loughborough-water-management",
    university: "Loughborough University",
    course: "MSc Water Management for Development",
    theme: "Science and technology for development",
    url: "https://www.lboro.ac.uk/study/postgraduate/masters-degrees/a-z/water-management-development-distance-learning-pt/",
  },
  {
    slug: "st-andrews-aquaculture",
    university: "University of St Andrews",
    course: "MSc Sustainable Aquaculture",
    theme: "Science and technology for development",
    url: "https://www.st-andrews.ac.uk/subjects/marine-biology/sustainable-aquaculture/",
  },
  {
    slug: "strathclyde-hydrogeology",
    university: "University of Strathclyde",
    course: "MSc Hydrogeology",
    theme: "Science and technology for development",
    url: "https://www.strath.ac.uk/courses/postgraduatetaught/hydrogeology/",
  },
  {
    slug: "open-university-global-development",
    university: "Open University",
    course: "MSc Global Development",
    theme: "Strengthening global peace, security and governance",
    url: "https://www.open.ac.uk/postgraduate/qualifications/f86",
  },
  {
    slug: "oxford-human-rights-law",
    university: "University of Oxford",
    course: "MSc International Human Rights Law",
    theme: "Strengthening global peace, security and governance",
    url: "https://www.ox.ac.uk/admissions/graduate/courses/msc-international-human-rights-law",
  },
  {
    slug: "portsmouth-journalism",
    university: "University of Portsmouth",
    course: "MA Journalism",
    theme: "Strengthening global peace, security and governance",
    url: "https://www.port.ac.uk/study/courses/postgraduate-taught/ma-journalism",
  },
  {
    slug: "portsmouth-economic-crime",
    university: "University of Portsmouth",
    course: "MSc Economic Crime",
    theme: "Strengthening global peace, security and governance",
    url: "https://www.port.ac.uk/study/courses/postgraduate-taught/msc-economic-crime",
  },
  {
    slug: "warwick-central-banking",
    university: "University of Warwick",
    course: "MSc Global Central Banking and Financial Regulation",
    theme: "Strengthening global peace, security and governance",
    url: "https://www.wbs.ac.uk/courses/masters/global-central-banking-and-financial-regulation/",
  },
  {
    slug: "imperial-mph",
    university: "Imperial College London",
    course: "MPH Public Health",
    theme: "Improving population health, health systems and capacity",
    url: "https://www.imperial.ac.uk/study/courses/postgraduate-taught/mph-online/",
  },
  {
    slug: "lancaster-healthcare-leadership",
    university: "Lancaster University",
    course: "MSc Healthcare Leadership",
    theme: "Improving population health, health systems and capacity",
    url: "https://www.lancaster.ac.uk/study/postgraduate/postgraduate-courses/healthcare-leadership-msc/2025/",
  },
  {
    slug: "lstmed-global-health",
    university: "Liverpool School of Tropical Medicine",
    course: "MSc Global Health",
    theme: "Improving population health, health systems and capacity",
    url: "https://www.lstmed.ac.uk/study/courses/msc-pgdip-pgcert-global-health",
  },
  {
    slug: "edinburgh-mph",
    university: "University of Edinburgh",
    course: "MPH Public Health",
    theme: "Improving population health, health systems and capacity",
    url: "https://postgraduate.degrees.ed.ac.uk/index.php?r=site/view&id=886",
  },
  {
    slug: "edinburgh-pain-management",
    university: "University of Edinburgh",
    course: "MSc Clinical Management of Pain",
    theme: "Improving population health, health systems and capacity",
    url: "https://postgraduate.degrees.ed.ac.uk/index.php?r=site/view&edition=2025&id=820",
  },
  {
    slug: "edinburgh-critical-care",
    university: "University of Edinburgh",
    course: "MSc Critical Care",
    theme: "Improving population health, health systems and capacity",
    url: "https://postgraduate.degrees.ed.ac.uk/index.php?r=site/view&edition=2025&id=975",
  },
  {
    slug: "edinburgh-clinical-trials",
    university: "University of Edinburgh",
    course: "MSc Clinical Trials",
    theme: "Improving population health, health systems and capacity",
    url: "https://study.ed.ac.uk/programmes/postgraduate-taught/809-clinical-trials-online-learning",
  },
  {
    slug: "edinburgh-patient-safety",
    university: "University of Edinburgh",
    course: "MSc Patient Safety and Clinical Human Factors",
    theme: "Improving population health, health systems and capacity",
    url: "https://study.ed.ac.uk/programmes/postgraduate-taught/962-patient-safety-and-clinical-human-factors-online-learning",
  },
  {
    slug: "edinburgh-data-science-health",
    university: "University of Edinburgh",
    course: "MSc Data Science for Health and Social Care",
    theme: "Improving population health, health systems and capacity",
    url: "https://postgraduate.degrees.ed.ac.uk/index.php?r=site/view&id=1041",
  },
  {
    slug: "edinburgh-epidemiology",
    university: "University of Edinburgh",
    course: "MSc Epidemiology",
    theme: "Improving population health, health systems and capacity",
    url: "https://postgraduate.degrees.ed.ac.uk/index.php?r=site/view&edition=2025&id=1042",
  },
  {
    slug: "edinburgh-internal-medicine",
    university: "University of Edinburgh",
    course: "MSc Internal Medicine",
    theme: "Improving population health, health systems and capacity",
    url: "https://postgraduate.degrees.ed.ac.uk/index.php?r=site/view&edition=2025&id=692",
  },
  {
    slug: "edinburgh-conservation-medicine",
    university: "University of Edinburgh",
    course: "MSc Conservation Medicine",
    theme: "Improving population health, health systems and capacity",
    url: "https://study.ed.ac.uk/programmes/postgraduate-taught/786-conservation-medicine-online-learning",
  },
  {
    slug: "edinburgh-breeding-genetics",
    university: "University of Edinburgh",
    course: "MSc Data-Driven Breeding and Genetics",
    theme: "Improving population health, health systems and capacity",
    url: "https://study.ed.ac.uk/programmes/postgraduate-taught/1134-data-driven-breeding-and-genetics-online-learning",
  },
  {
    slug: "edinburgh-animal-health",
    university: "University of Edinburgh",
    course: "MSc International Animal Health",
    theme: "Improving population health, health systems and capacity",
    url: "https://study.ed.ac.uk/programmes/postgraduate-taught/241-international-animal-health-online-learning",
  },
  {
    slug: "edinburgh-one-health",
    university: "University of Edinburgh",
    course: "MSc One Health",
    theme: "Improving population health, health systems and capacity",
    url: "https://study.ed.ac.uk/programmes/postgraduate-taught/814-one-health-online-learning",
  },
  {
    slug: "liverpool-mph",
    university: "University of Liverpool",
    course: "MPH Public Health",
    theme: "Improving population health, health systems and capacity",
    url: "https://online.liverpool.ac.uk/programmes/master-of-public-health/",
  },
  {
    slug: "liverpool-mph-global-health",
    university: "University of Liverpool",
    course: "MPH Public Health (Global Health)",
    theme: "Improving population health, health systems and capacity",
    url: "https://online.liverpool.ac.uk/programmes/master-of-public-health-online-global-health/",
  },
  {
    slug: "liverpool-mph-health-economics",
    university: "University of Liverpool",
    course: "MPH Public Health (Health Economics and Policy)",
    theme: "Improving population health, health systems and capacity",
    url: "https://online.liverpool.ac.uk/programmes/master-of-public-health-health-economics-and-policy/",
  },
  {
    slug: "liverpool-mph-mental-health",
    university: "University of Liverpool",
    course: "MPH Public Health (Global Mental Health)",
    theme: "Improving population health, health systems and capacity",
    url: "https://online.liverpool.ac.uk/programmes/master-of-public-health-global-mental-health/",
  },
  {
    slug: "stirling-dementia",
    university: "University of Stirling",
    course: "MSc Dementia Studies",
    theme: "Improving population health, health systems and capacity",
    url: "https://www.stir.ac.uk/courses/pg-taught/dementia-studies-online/",
  },
  {
    slug: "strathclyde-rehabilitation",
    university: "University of Strathclyde",
    course: "MSc Rehabilitation Studies",
    theme: "Improving population health, health systems and capacity",
    url: "https://www.strath.ac.uk/courses/postgraduatetaught/prostheticsorthoticsrehabilitationstudies/",
  },
  {
    slug: "open-university-environmental-mgmt",
    university: "Open University",
    course: "MSc Environmental Management",
    theme: "Strengthening resilience and responses to crises",
    url: "https://www.open.ac.uk/postgraduate/qualifications/f65",
  },
  {
    slug: "edinburgh-climate-change",
    university: "University of Edinburgh",
    course: "MSc Climate Change Management",
    theme: "Strengthening resilience and responses to crises",
    url: "https://study.ed.ac.uk/programmes/postgraduate-taught/899-climate-change-management-online-learning",
  },
  {
    slug: "edinburgh-conservation-genetics",
    university: "University of Edinburgh",
    course: "MSc Applied Conservation Genetics with Wildlife Forensics",
    theme: "Strengthening resilience and responses to crises",
    url: "https://study.ed.ac.uk/programmes/postgraduate-taught/954-applied-conservation-genetics-with-wildlife-forensics-online",
  },
  {
    slug: "edinburgh-biodiversity",
    university: "University of Edinburgh",
    course: "MSc Biodiversity, Wildlife and Ecosystem Health",
    theme: "Strengthening resilience and responses to crises",
    url: "https://study.ed.ac.uk/programmes/postgraduate-taught/646-biodiversity-wildlife-and-ecosystem-health-online-learning",
  },
  {
    slug: "edinburgh-food-security",
    university: "University of Edinburgh",
    course: "MSc Global Food Security and Nutrition",
    theme: "Strengthening resilience and responses to crises",
    url: "https://study.ed.ac.uk/programmes/postgraduate-taught/959-global-food-security-and-nutrition-online-learning",
  },
  {
    slug: "edinburgh-infectious-diseases",
    university: "University of Edinburgh",
    course: "MSc Global Health and Infectious Diseases",
    theme: "Strengthening resilience and responses to crises",
    url: "https://study.ed.ac.uk/programmes/postgraduate-taught/413-global-health-and-infectious-diseases-online-learning",
  },
  {
    slug: "sussex-sustainable-development",
    university: "University of Sussex",
    course: "MSc Sustainable Development",
    theme: "Strengthening resilience and responses to crises",
    url: "https://study-online.sussex.ac.uk/online-courses/sustainable-development-msc/scholarship",
  },
  {
    slug: "york-humanitarian-affairs",
    university: "University of York",
    course: "MSc International Humanitarian Affairs",
    theme: "Strengthening resilience and responses to crises",
    url: "https://www.york.ac.uk/study/postgraduate-taught/courses/msc-international-humanitarian-affairs-online/",
  },
];

function commonwealthDistanceLeafProgrammes() {
  return COMMONWEALTH_DISTANCE_COURSES.map((entry) => ({
    externalId: `commonwealth-distance-${entry.slug}`,
    title: `Commonwealth Distance Learning — ${entry.course} (${entry.university})`,
    organizationName: entry.university,
    country: "United Kingdom",
    hostCountry: "United Kingdom",
    degreeLevel: "master",
    fieldOfStudy: entry.theme,
    fundingType: "fully_funded",
    applicationStartDate: null,
    applicationEndDate: null,
    deadline: null,
    url: entry.url,
    applicationUrl: entry.url,
    sourceUrl: entry.url,
    description: distanceDescription(entry),
    eligibleRegions: ["africa", "commonwealth", "developing"],
  }));
}

module.exports = {
  COMMONWEALTH_DISTANCE_COURSES,
  CSC_DISTANCE_SCHEME,
  CSC_DISTANCE_COURSES,
  commonwealthDistanceLeafProgrammes,
};
